kind: Service
apiVersion: v1
metadata:
  name: node-sample-app-service
spec:
  selector:
    app: node-sample-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sample-app
  labels:
    app: node-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-sample-app
  template:
    metadata:
      labels:
        app: node-sample-app
    spec:
      imagePullSecrets:
      - name: []
      containers:
      - name: node-sample-app
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
